const CATEGORIES_ACTION_TYPES = Object.freeze({
    FETCH_CATEGORIES_START: Symbol("category/FETCH_CATEGORIES_START"),
    FETCH_CATEGORIES_SUCCESS: Symbol("category/FETCH_CATEGORIES_SUCCESS"),
    FETCH_CATEGORIES_FAILED: Symbol("category/FETCH_CATEGORIES_FAILED"),
})

export default CATEGORIES_ACTION_TYPES;